// catalog/frontends/vue-vite/patterns/UserIdentification.vue
<script setup lang="ts">
import { datadogRum } from '@datadog/browser-rum';
import { onMounted } from 'vue';

const props = defineProps<{ userId: string; email: string }>();

onMounted(() => {
  datadogRum.setUser({ id: props.userId, email: props.email, name: props.email.split('@')[0] });
});
</script>

<template>
  <span />
</template>

// catalog/frontends/react-vite/patterns/UserIdentification.tsx
import { datadogRum } from '@datadog/browser-rum';
import { useEffect } from 'react';

// Pattern: RUM user identification — track sessions by user
// Adapt: call after your authentication flow resolves
export default function UserIdentification({ userId, email }: { userId: string; email: string }) {
  useEffect(() => {
    datadogRum.setUser({ id: userId, email, name: email.split('@')[0] });
  }, [userId, email]);

  return null;
}
