// catalog/frontends/react-vite/template/src/App.tsx
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import HealthCheck from './components/HealthCheck';
import ChatWidget from './components/ChatWidget';

const FEATURE_CHAT = import.meta.env.VITE_FEATURE_CHAT === 'true';

function App() {
  return (
    <BrowserRouter>
      <div className="min-h-screen bg-base-200">
        <div className="navbar bg-primary text-primary-content px-4">
          <div className="navbar-start">
            <span className="font-bold tracking-tight">Demo App</span>
          </div>
          <div className="navbar-end">
            <Link to="/" className="btn btn-ghost btn-sm text-primary-content">Home</Link>
          </div>
        </div>
        <main className="p-6">
          <Routes>
            <Route path="/" element={<HealthCheck />} />
          </Routes>
        </main>
      </div>
      {FEATURE_CHAT && <ChatWidget />}
    </BrowserRouter>
  );
}

export default App;

// catalog/frontends/vue-vite/template/src/App.vue
<script setup lang="ts">
import { RouterView, RouterLink } from 'vue-router';
import ChatWidget from './components/ChatWidget.vue';

const featureChat = import.meta.env.VITE_FEATURE_CHAT === 'true';
</script>

<template>
  <div class="min-h-screen bg-base-200">
    <div class="navbar bg-primary text-primary-content px-4">
      <div class="navbar-start">
        <span class="font-bold tracking-tight">Demo App</span>
      </div>
      <div class="navbar-end">
        <RouterLink to="/" class="btn btn-ghost btn-sm text-primary-content">Home</RouterLink>
      </div>
    </div>
    <main class="p-6">
      <RouterView />
    </main>
  </div>
  <ChatWidget v-if="featureChat" />
</template>
