// catalog/frontends/react-vite/patterns/CustomActionButton.tsx
import { datadogRum } from '@datadog/browser-rum';

// Pattern: RUM custom action — track user interactions
// Adapt: use domain-relevant action names and context
export default function CustomActionButton({ label, actionName }: { label: string; actionName: string }) {
  const handleClick = () => {
    datadogRum.addAction(actionName, { label, timestamp: Date.now() });
  };

  return <button onClick={handleClick}>{label}</button>;
}

// catalog/frontends/vue-vite/patterns/CustomActionButton.vue
<script setup lang="ts">
import { datadogRum } from '@datadog/browser-rum';

const props = defineProps<{ label: string; actionName: string }>();

function handleClick() {
  datadogRum.addAction(props.actionName, { label: props.label, timestamp: Date.now() });
}
</script>

<template>
  <button @click="handleClick">{{ label }}</button>
</template>
