// catalog/frontends/react-vite/patterns/ErrorBoundary.tsx
import { datadogRum } from '@datadog/browser-rum';
import { Component, ReactNode } from 'react';

// Pattern: Error boundary with RUM error reporting
// Adapt: wrap domain-critical UI sections
interface Props { children: ReactNode; }
interface State { hasError: boolean; }

export default class ErrorBoundary extends Component<Props, State> {
  state: State = { hasError: false };

  static getDerivedStateFromError() { return { hasError: true }; }

  componentDidCatch(error: Error) {
    datadogRum.addError(error, { source: 'component' });
  }

  render() {
    if (this.state.hasError) return <div>Something went wrong.</div>;
    return this.props.children;
  }
}

// catalog/frontends/vue-vite/patterns/ErrorBoundary.vue
<script setup lang="ts">
import { datadogRum } from '@datadog/browser-rum';
import { ref, onErrorCaptured } from 'vue';

const hasError = ref(false);

onErrorCaptured((error: Error) => {
  datadogRum.addError(error, { source: 'component' });
  hasError.value = true;
  return false;
});
</script>

<template>
  <div v-if="hasError">Something went wrong.</div>
  <slot v-else />
</template>
